// AUTO-GENERATED FROM inventory-template.json
// Last updated: 2025-10-19T21:28:08.668Z
// DO NOT EDIT THIS FILE MANUALLY - Edit inventory-template.json instead

import { Building, InventoryItem } from './types';

export const BUILDINGS_DATA: Building[] = [
    {
        id: 'building-1',
        name: 'Building 1 - Silver',
        status: 'In Progress',
        path: 'M 150,50 L 150,200 L 350,200 L 350,50 Z',
    },
    {
        id: 'building-2',
        name: 'Building 2 - Green',
        status: 'In Progress',
        path: 'M 400,80 L 400,180 L 550,180 L 550,80 Z',
    },
    {
        id: 'building-3',
        name: 'Building 3 - Red',
        status: 'Pending',
        path: 'M 200,230 L 200,350 L 500,350 L 500,230 Z',
    },
    {
        id: 'building-4',
        name: 'Building 4 - Blue',
        status: 'Pending',
        path: 'M 100,280 L 100,380 L 180,380 L 180,280 Z',
    },
];

export const INVENTORY_DATA: InventoryItem[] = [
    {
        "id": "ITEM001",
        "buildingId": "building-1",
        "buildingName": "Building 1 - Silver",
        "name": "Dual Jet Drill Presses with Workbench",
        "description": "Two industrial Jet brand drill presses mounted on shared workbench table. Heavy-duty construction suitable for precision drilling operations. Workbench provides integrated workspace connecting both units. Photographed October 2025 during factory inventory.",
        "specifications": "Dual drill press setup, shared workbench table integration, Jet brand equipment, appears to be floor-standing models with extended work surface.",
        "condition": "Fair",
        "conditionRating": 3,
        "status": "For Sale",
        "reviewStatus": "Pending",
        "reviewedBy": "",
        "reviewDate": "2025-10-21",
        "reviewNotes": "",
        "value": 3500,
        "location": "Building 1, Main Floor",
        "serialNumber": "To be documented on-site",
        "imageUrl": "/assets/inventory/ITEM001_jet_drill_presses.jpg",
        "photoUrl": "/assets/inventory/ITEM001_jet_drill_presses.jpg",
        "aiAnalysis": "Dual Jet drill press setup photographed Oct 2025. Two units connected via shared workbench table. Jet brand equipment known for reliability. Estimated market value: $3,000-$4,500 for dual setup with integrated workspace.",
        "notes": "Real factory equipment photographed Oct 21, 2025. Two drill presses with connecting workbench table. Needs detailed inspection for model numbers and operational status."
    },
    {
        "id": "ITEM002",
        "buildingId": "building-1",
        "buildingName": "Building 1 - Silver",
        "name": "Industrial Milling Machine - Precision Machining Center",
        "description": "Large industrial milling machine with substantial table and vertical head. Heavy-duty construction suitable for production machining operations. Equipment photographed during October 2025 factory inventory.",
        "specifications": "Vertical mill configuration, estimated table size 16x60+ inches. Appears to have power feed on X/Y axes. Heavy cast construction with tooling visible.",
        "condition": "Fair",
        "conditionRating": 3,
        "status": "For Sale",
        "reviewStatus": "Pending",
        "reviewedBy": "",
        "reviewDate": "2025-10-21",
        "reviewNotes": "",
        "value": 8500,
        "location": "Building 1, Main Floor, Center Section",
        "serialNumber": "To be documented on-site",
        "imageUrl": "https://via.placeholder.com/400x300/334155/f59e0b?text=Milling+Machine",
        "photoUrl": "https://via.placeholder.com/400x300/334155/f59e0b?text=Milling+Machine",
        "aiAnalysis": "Industrial milling machine photographed Oct 2025. Vertical configuration with substantial table size. Appears to be American-made equipment. Some surface oxidation visible. Estimated market value: $7,000-$12,000 based on size and condition.",
        "notes": "Real factory equipment. Photos pending upload. Priority item for detailed specs collection including motor HP, table travel limits, and spindle taper."
    },
    {
        "id": "ITEM003",
        "buildingId": "building-1",
        "buildingName": "Building 1 - Silver",
        "name": "Heavy Industrial Press - Metal Forming Equipment",
        "description": "Large industrial press for metal forming, stamping, or assembly operations. Substantial frame construction with hydraulic or mechanical operation. Photographed during October 2025 factory inventory assessment.",
        "specifications": "Estimated tonnage: 50-150 tons based on frame size. Appears to have powered operation (hydraulic or mechanical). Heavy duty construction with working platform access.",
        "condition": "Fair",
        "conditionRating": 3,
        "status": "For Sale",
        "reviewStatus": "Pending",
        "reviewedBy": "",
        "reviewDate": "2025-10-21",
        "reviewNotes": "",
        "value": 15000,
        "location": "Building 1, Main Floor, West Section",
        "serialNumber": "To be documented on-site",
        "imageUrl": "https://via.placeholder.com/400x300/334155/10b981?text=Industrial+Press",
        "photoUrl": "https://via.placeholder.com/400x300/334155/10b981?text=Industrial+Press",
        "aiAnalysis": "Heavy industrial press photographed Oct 2025. Large frame construction indicates substantial tonnage capacity. Equipment appears suitable for metal forming, stamping, or heavy assembly work. Market value range: $12,000-$20,000 depending on tonnage rating and condition verification.",
        "notes": "Real factory equipment. Photos pending upload. High-value item requiring detailed inspection for manufacturer plate, tonnage rating, and operational status."
    }
];

// Statistics (for reference)
export const INVENTORY_STATS = {
    totalItems: 3,
    totalValue: 27000,
    building1Items: 3,
    building2Items: 0,
    building3Items: 0,
    building4Items: 0,
    lastUpdated: '10/21/2025, 11:36:00 PM'
};

// Status color mapping for UI
export const STATUS_COLORS = {
    'For Sale': 'bg-emerald-500/20 text-emerald-400 border-emerald-500',
    'Sold': 'bg-blue-500/20 text-blue-400 border-blue-500',
    'Pending Review': 'bg-yellow-500/20 text-yellow-400 border-yellow-500',
    'Reserved': 'bg-purple-500/20 text-purple-400 border-purple-500',
    'Scrap': 'bg-red-500/20 text-red-400 border-red-500',
    'In Progress': 'bg-orange-500/20 text-orange-400 border-orange-500',
    'Pending': 'bg-gray-500/20 text-gray-400 border-gray-500'
};

// Map status color mapping for PropertyMap component
export const MAP_STATUS_COLORS: Record<string, string> = {
    'In Progress': '#f97316', // Orange
    'Completed': '#10b981', // Green
    'Pending': '#6b7280', // Gray
    'For Sale': '#10b981', // Green
    'Sold': '#3b82f6', // Blue
    'Reserved': '#8b5cf6' // Purple
};
